version: '3.8'

services:
  trading_bot:
    build:
      context: .
    container_name: binance_trading_bot
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
    volumes:
      - ./src:/app
    restart: unless-stopped
